---

- name: set time zone
  community.general.timezone:
    name: '{{ system_timezone }}'
  tags:
    - timezone

- name: remove unneeded ntp clients
  ansible.builtin.package:
    name: chrony,ntp
    state: absent
  when: systemd_timesyncd_purge_legacy_packages

- name: install systemd
  ansible.builtin.package:
    name: systemd

- name: configure systemd-timesyncd
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  register: __systemd_timesyncd_configuration

- name: install systemd-timesyncd
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  tags:
    - service
    - service-timesyncd
    - timesyncd-service

- name: enable systemd-timesyncd service and assure it is started
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: yes
    state: >-
      {{
        __systemd_timesyncd_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  tags:
    - service
    - service-timesyncd
    - timesyncd-service

...
